#!/bin/bash
export LC_ALL=C

dir=$(pwd)

mkdir SDF
cd $dir/SDF

git clone -o C https://github.com/keithbennett/SDF_C.git
git clone -o utilities https://github.com/keithbennett/SDF_utilities.git

cd $dir/SDF/C
make 

cd $dir/SDF/utilities
./build

wget -q -O data.zip "https://zenodo.org/record/3707924/files/data.zip?download=1"
unzip data.zip
rm data.zip
